import react from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'
import { defineConfig } from 'vite'
import { VitePWA } from 'vite-plugin-pwa'

// https://vite.dev/config/
export default defineConfig({
  plugins: [
    react(),
    tailwindcss(),
    VitePWA({
      registerType: 'autoUpdate',
      injectRegister: false,
      manifest: {
        name: 'Palmtwist',
        short_name: 'Palmtwist',
        description: "A Rubik's Cube you control with your hands. Everything runs in your browser.",
        theme_color: '#16171B',
        background_color: '#16171B',
        display: 'standalone',
        // Reuses the existing favicon.svg rather than generating a whole PNG
        // icon set for one asset -- modern browsers accept an SVG manifest
        // icon with sizes "any".
        icons: [{ src: '/favicon.svg', sizes: 'any', type: 'image/svg+xml' }],
      },
      workbox: {
        // The MediaPipe WASM runtime (~34MB, generated by
        // scripts/setup-mediapipe.mjs) and the .task model (~7.5MB) are
        // deliberately excluded from the precache manifest: they're only
        // needed by the opt-in "Hands" input mode, not for first paint, and
        // precaching them would bloat the service worker's install step far
        // beyond what the core app needs. A runtime CacheFirst rule still
        // lets them work offline once a user has opened Hands mode once.
        // Also left out: the other puzzles that ship inside cubing.js (megaminx,
        // 4x4x4 and so on). The app never loads them, so installing them into
        // every visitor's cache would be about 270 kB of waste.
        globIgnores: [
          'mediapipe/**',
          'models/**',
          'assets/puzzles-dynamic-{4x4x4,megaminx,unofficial,side-events}-*',
          'assets/puzzle-geometry-*',
        ],
        runtimeCaching: [
          {
            urlPattern: /\/(mediapipe|models)\//,
            handler: 'CacheFirst',
            options: {
              cacheName: 'handcube-gesture-assets',
              expiration: { maxEntries: 20, maxAgeSeconds: 60 * 60 * 24 * 365 },
            },
          },
        ],
      },
    }),
  ],
})
